const SliderItemList2=[
    {
        id:1,
        title:'Trending deal',
        image:'./categoryList/eye-brush.jpg',
        imageTitle:'deal',
        linkTitle:'See more',
        link:'',
    },
    {
        id:2,
        title:'Prime Free One Day Delivery',
        image:'./categoryList/dettol-liquid.jpg',
        imageTitle:'one day delivery item',
        linkTitle:'Select Item & area. Learn more',
        link:'',
    },
    {
        id:3,
        title:"Father's Day Gift Shop",
        image:'./categoryList/explorer.jpg',
        imageTitle:'father day gift',
        linkTitle:'Shop now',
        link:'',
    },
    
    {
        id:4,
        title:"Father's Day Gift Shop",
        image:'./categoryList/perfume.jpg',
        imageTitle:'father day gift',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:5,
        title:"Top Deal",
        image:'./categoryList/perfume2.jpg',
        imageTitle:'Laptop',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:6,
        title:"Deal on Kindle e-reader",
        image:'./categoryList/cetaphil.jpg',
        imageTitle:'tablet',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:7,
        title:"Deal on electronic Device",
        image:'./categoryList/chasis.jpg',
        imageTitle:'earpod',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:8,
        title:"New movies: Thirteen lives",
        image:'./categoryList/antigen.jpg',
        imageTitle:'movie',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:9,
        title:"New movies: Thirteen lives",
        image:'./categoryList/hair-dryer.jpg',
        imageTitle:'movie',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:10,
        title:"New movies: Thirteen lives",
        image:'./categoryList/nail-oil.jpg',
        imageTitle:'movie',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:11,
        title:"New movies: Thirteen lives",
        image:'./categoryList/lash.jpg',
        imageTitle:'movie',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:12,
        title:"New movies: Thirteen lives",
        image:'./categoryList/olaplex.jpg',
        imageTitle:'movie',
        linkTitle:'Shop now',
        link:'',
    },
]

export default SliderItemList2;