const Branches=()=>[
    {
        id:1,
        countryName:"Brazil",
    },
    {
        id:2,
        countryName:"Cananda",
    },
    {
        id:3,
        countryName:"China",
    },
    {
        id:4,
        countryName:"France",
    },
    {
        id:5,
        countryName:"Germany",
    },
    {
        id:6,
        countryName:"India",
    },
    {
        id:7,
        countryName:"Italy",
    },
    {
        id:8,
        countryName:"Japan",
    },
    {
        id:9,
        countryName:"Mexico",
    },
    {
        id:10,
        countryName:"Netharland",
    },
    {
        id:11,
        countryName:"Poland",
    },
    {
        id:12,
        countryName:"Singapore",
    },
    {
        id:13,
        countryName:"Spain",
    },
    {
        id:14,
        countryName:"Turkey",
    },
    {
        id:15,
        countryName:"United Arab Emirates",
    },
    {
        id:16,
        countryName:"United Kingdom",
    },
    {
        id:17,
        countryName:"United States",
    },
]
export default Branches;