const ItemCategoryList=[
    {
        id:1,
        title:'Trending deal',
        image:'./categoryList/laptop.jpg',
        imageTitle:'deal',
        linkTitle:'See more',
        link:'',
    },
    {
        id:2,
        title:'Prime Free One Day Delivery',
        image:'./categoryList/one-day-delivery-itme.jpg',
        imageTitle:'one day delivery item',
        linkTitle:'Select Item & area. Learn more',
        link:'',
    },
    {
        id:3,
        title:"Father's Day Gift Shop",
        image:'./categoryList/father-day-gift.jpg',
        imageTitle:'father day gift',
        linkTitle:'Shop now',
        link:'',
    },{
        id:4,
        title:"Sign in for your best experience",
        image:'',
        imageTitle:'',
        linkTitle:'Sign in securely',
        link:'',
    },
    {
        id:5,
        title:"Father's Day Gift Shop",
        image:'./categoryList/father-day-gift.jpg',
        imageTitle:'father day gift',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:6,
        title:"Top Deal",
        image:'./categoryList/laptop.jpg',
        imageTitle:'Laptop',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:7,
        title:"Deal on Kindle e-reader",
        image:'./categoryList/tablet.jpg',
        imageTitle:'tablet',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:8,
        title:"Deal on electronic Device",
        image:'./categoryList/earpod.jpg',
        imageTitle:'earpod',
        linkTitle:'Shop now',
        link:'',
    },
    {
        id:9,
        title:"New movies: Thirteen lives",
        image:'./categoryList/movie.jpg',
        imageTitle:'movie',
        linkTitle:'Shop now',
        link:'',
    },
]

export default ItemCategoryList;